# Generated by Django 5.0.4 on 2024-04-25 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('occasion', models.CharField(max_length=100, verbose_name='Повод')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='План сбора')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Собрано')),
                ('contributors_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во пожертвовавших')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collect_covers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата окончания сбора')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='published', max_length=10, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'Сборы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collective_donations.collect', verbose_name='Сбор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
