# Generated by Django 5.0.4 on 2024-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картой'), ('sbp', 'СБП'), ('mobile transfer', 'Перевод на телефон')], default='card', max_length=30, verbose_name='Методо оплаты'),
        ),
    ]
