# Generated by Django 5.0.4 on 2024-04-27 09:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_donations', '0007_payment_payment_id_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-create'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='collect',
            name='end_datetime',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 27))], verbose_name='Дата окончания сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма в рублях, максимальное занчение: 99999999.99', max_digits=10, verbose_name='План сбора'),
        ),
    ]
