services:

  donations_backend:
    build: .
    container_name: donations_backend
    command: sh /app/startup.sh
    env_file: .env
    depends_on:
      - donations_db
    volumes:
      - static:/backend_static/static
      - media:/app/media

  donations_db:
    image: postgres:15-alpine
    container_name: donations_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  donations_nginx:
    build: ./nginx/
    container_name: donations_nginx
    env_file: .env
    depends_on:
      - donations_backend
    ports:
      - 8000:80
    volumes:
      - static:/donations_static
      - media:/donations_media

volumes:
  pg_data:
  static:
  media:
