services:

  donations_backend:
    build: .
    container_name: donations_backend
    command: sh /app/startup.sh
    env_file: .env
    depends_on:
      - donations_db
    volumes:
      - static:/backend_static/static
      - media:/app/media
      - ./sent_emails:/app/sent_emails

  donations_db:
    image: postgres:15-alpine
    container_name: donations_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  donations_nginx:
    build: ./nginx/
    container_name: donations_nginx
    env_file: .env
    depends_on:
      - donations_backend
    ports:
      - 8000:80
    volumes:
      - static:/donations_static
      - media:/donations_media

  donations_redis:
    container_name: donations_redis
    image: redis:7.4.0
    expose:
      - 6379
    volumes:
      - redis-data:/data

  donations_celery:
    container_name: donations_celery
    build:  .
    env_file: .env
    command: sh /app/selery_startup.sh
    depends_on:
      - donations_redis
      - donations_db
      - donations_backend
    volumes:
      - .:/app

volumes:
  pg_data:
  static:
  media:
  redis-data:
