# Generated by Django 5.0.4 on 2024-04-26 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_donations', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/collect_covers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картой'), ('sbp', 'СБП'), ('mobile transfer', 'Перевод на телефон')], default='card', max_length=15, verbose_name='Методо оплаты'),
        ),
    ]
