# Generated by Django 5.0.4 on 2024-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_donations', '0003_alter_collect_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='end_datetime',
            field=models.DateField(verbose_name='Дата окончания сбора'),
        ),
    ]
