# Generated by Django 5.0.4 on 2024-04-27 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_donations', '0010_alter_payment_collect_alter_payment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collect',
            index=models.Index(fields=['slug'], name='collective__slug_912051_idx'),
        ),
    ]
