# Generated by Django 5.0.4 on 2024-04-28 10:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_donations', '0013_alter_payment_collect_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='end_datetime',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 28))], verbose_name='Дата окончания сбора'),
        ),
    ]
