# Generated by Django 5.0.4 on 2024-08-21 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collective_donations", "0016_alter_collect_end_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="collected_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Собрано",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Сумма в рублях, максимальное занчение: 99999999.99",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="План сбора",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Сумма",
            ),
        ),
    ]
