# Generated by Django 5.0.4 on 2024-04-26 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_user.jpg', upload_to='user_avatar', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Аватар'),
        ),
    ]
