# Generated by Django 5.0.4 on 2024-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_donationsuser_paternal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
