# Generated by Django 5.0.4 on 2024-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_donationsuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsuser',
            name='bio',
            field=models.TextField(blank=True, max_length=400, verbose_name='О себе'),
        ),
    ]
