# Generated by Django 5.0.4 on 2024-08-20 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_alter_donationsuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationsuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="images/default_user.jpg",
                null=True,
                upload_to="images/user_avatar",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg", "jpeg")
                    )
                ],
                verbose_name="Аватар",
            ),
        ),
    ]
